version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db:db
    environment:
      PORT: 8080
      SECRET: ${SECRET}
      DB_URL: postgres://postgres:postgres@db:5432/medods_test_task
  
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medods_test_task
