services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - migrate
    environment:
      PORT: 8080
      SECRET: ${SECRET}
      DB_URL: postgres://postgres:postgres@db:5432/medods_test_task
  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command:
      [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/medods_test_task?sslmode=disable", "up" ]
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medods_test_task
